version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  gadgetapp:
    build: .
    command: >
      bash -c "python3 manage.py migrate &&
               python3 manage.py inspectdb &&
               python3 manage.py init_db &&
               python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/gadgetapp
    ports:
      - 8000:8000
    env_file:
      - ./gadgetapp.env
    depends_on:
      db:
        condition: service_healthy
volumes:
  postgres_db: