# Base image with GPU dependencies
FROM nvcr.io/nvidia/pytorch:20.09-py3
WORKDIR /app
# Load 3rd party libraries
COPY ./requirements.txt /app/requirements.txt
RUN pip install --upgrade pip
RUN pip install -r /app/requirements.txt
# Load LMI AI Solutions software
RUN git clone https://github.com/lmitechnologies/LMI_AI_Solutions.git
RUN git -C /app/LMI_AI_Solutions reset --hard 41faca067a1ea5944ed73945e0e1972d3053991a