# Generated by Django 4.0.2 on 2022-09-14 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userautomationconfig',
            name='mark_silver',
        ),
        migrations.RemoveField(
            model_name='userpipelineconfig',
            name='confidence_silver',
        ),
    ]
